const prodacts = [
  {
    id: 1,
    name: "77,99 ₽",
    category: "FruitС картой",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 89,
    rating: 5.1,
    discount: 0,
    image: "../images/before-card1.png",
  },
  {
    id: 2,
    name: "44,50 ₽",
    category: "С картой",
    description: "Г/Ц Блинчики с мясом вес, Россия",
    price: "50,50 ₽",
    category2: "Обычная",
    rating: 2,
    discount: 20,
    image: "../images/card-fruit1.png",
  },
  {
    id: 3,
    name: "44,50 ₽",
    category: "С картой",
    description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное",
    price: "50,50 ₽",
    category2: "Обычная",
    rating: 3,
    discount: 20,
    image: "../images/card-malako2.png",
  },
  {
    id: 4,
    name: "44,50 ₽",
    category: "С картой",
    description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное",
    price: "50,50 ₽",
    category2: "Обычная",
    rating: 5,
    discount: 20,
    image: "../images/bottle-meat3.png",
  },
  {
    id: 5,
    name: "44,50 ₽",
    category: "С картой",
    description: "Сосиски вареные МЯСНАЯ ИСТОРИЯ Молочные и С сыро...",
    price: "50,50 ₽",
    category2: "Обычная",
    rating: 4,
    discount: 20,
    image: "../images/bottle2.png",
  },
  {
    id: 6,
    name: "159,99 ₽",
    category: "Dairy",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 91,
    rating: 5.2,
    discount: 50,
    image: "../images/bottle2.png",
  },
  {
    id: 7,
    name: "599,99 ₽",
    category: "Meat",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 68,
    rating: 5.3,
    discount: 20,
    image: "../images/novinka-card1.png",
  },
  {
    id: 8,
    name: "49,39 ₽",
    category: "Dessert",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 61,
    rating: 5.4,
    discount: 20,
    image: "../images/card-malako2.png",
  },
  {
    id: 9,
    name: "599,99 ₽",
    category: "Dessert",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 98,
    rating: 2,
    discount: 20,
    image: "../images/novinka-card1.png",
  },
  {
    id: 10,
    name: "44,50 ₽",
    category: "Dairy",
    description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
    price: 79,
    rating: 5,
    discount: 0,
    image: "../images/bottle-meat3.png",
  },
  {
    id: 11,
    name: "159,99 ₽",
    category: "Meat",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 89,
    rating: 2,
    discount: 50,
    image: "../images/bottle2.png",
  },
  {
    id: 12,
    name: "49,39 ₽",
    category: "Fruit",
    description: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    price: 61,
    rating: 2,
    discount: 20,
    image: "../images/card-malako2.png",
  },
];
